---
title: "Test1"
output: pdf_document
---

$\beta_{1}$ = Season

$\beta_{2}$ = year

$\beta_{3}$ = month

$\beta_{4}$ = hour

$\beta_{5}$ = holiday

$\beta_{6}$ = weekday

$\beta_{7}$ = 


```{r setup, include=FALSE}
library(tidyverse)


dataset = read.csv("hour.csv")



convert_hour_to_day <- function(hour){
  require(tidyverse)
  day = hour %>%
    group_by(dteday, season, yr, mnth, holiday, weekday, workingday) %>%
    summarize(weathersit = as.integer(round(mean(weathersit))),
              temp = mean(temp),
              atemp = mean(atemp),
              hum = mean(hum),
              windspeed = mean(windspeed),
              casual = sum(casual),
              registered = sum(registered),
              cnt = sum(cnt))
  day = tibble::rowid_to_column(day, "instant")
  return(day)
}
```

```{r}
quibble <- function(x, q = c(0.25, 0.5, 0.75)) {
  tibble(x = quantile(x, q), q = q)
}

plot_by_hour <- function(hour, variable, quantiles = c(0.10, 0.25, 0.5, 0.75, 0.90)){
  require(tidyverse)
  require(scales)
  data = hour %>%
    group_by(hr) %>%
    summarise(x = quibble(get(variable), quantiles))
  data = tibble(hr = as.character(data$hr), x = data$x$x, q = data$x$q)
  quant_title = paste(ordinal(quantiles*100), collapse = ", ") 
  quant_title = paste0(quant_title, " percentile ", variable, " of each hour of day")
  plo = ggplot(data, aes(x = reorder(hr, sort(as.numeric(hr))), y = x)) + 
    theme_bw() +
    geom_boxplot(aes(fill = reorder(hr, sort(as.numeric(hr))))) +
    xlab("Hour of Day") +
    ylab(variable) +
    theme(legend.position = "none") +
    ggtitle(quant_title) 
  return(plo)
}

plot_by_hour(dataset, "cnt")
ggsave("cnt.png")
plot_by_hour(dataset, "registered")
ggsave("registered.png")
plot_by_hour(dataset, "casual")
ggsave("casual.png")


```

```{r}
dataset %>% glimpse()

day = convert_hour_to_day(dataset)

day %>% glimpse()
```


```{r}
one = lm(cnt ~ season + yr + mnth + hr + holiday + weekday + weathersit + temp + atemp + hum + windspeed, data = dataset)


full_cnt = lm(cnt ~ factor(season) + yr + factor(mnth) +  factor(hr) + holiday + factor(weekday) + factor(weathersit) + temp + atemp + hum + windspeed, data = dataset)

summary(full_cnt)
anova(full_cnt)

full_casual = lm(casual ~  factor(season) + yr + factor(mnth) +  factor(hr) + holiday + factor(weekday) + factor(weathersit) + temp + atemp + hum + windspeed, data = dataset)

summary(full_casual)
anova(full_casual)

full_registered = lm(registered ~ factor(season) + yr + factor(mnth) +  factor(hr) + holiday + factor(weekday) + factor(weathersit) + temp + atemp + hum + windspeed, data = dataset)

summary(full_registered)
anova(full_registered)
```

```{r}
round(cor(dataset[3:17]), digits = 3)
```

